# Documentation website
title: HTTP Structured Fields
tagline: "Work with HTTP Structured Fields in PHP."
description: "A framework-agnostic PHP library that allows you to parse, serialize, create, update and validate HTTP Structured Fields in PHP following RFC9651 and RFC8941."
# Github repository
package: 'bakame/http-structured-fields'
repository_url: 'https://github.com/bakame-php/http-structured-fields'
release_major: '2.0'
version: 2.0.0
support: 'Once a new major version is released, the previous stable release remains supported for six more months with patches and security fixes.'
releases:
    next:
        version: '2.0'
        requires: 'PHP >= 8.1.0'
        documentation_link: '/2.0/'
    current:
        version: '1.0'
        requires: 'PHP >= 8.1.10'
        documentation_link: '/1.0/'
